spring:
  application:
    name: 'config'
  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/mikegrif/ms-configs.git'
          default-label: main
          timeout: 10
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: 'localhost'
    port: 5672
    username: 'guest'
    password: 'guest'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readiness:
      enabled: true
    liveness:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true

encrypt:
  key: 'just4MicroserviceSecret'

server:
  port: 8071
