spring:
  application:
    name: 'config'
  profiles:
    active: native

  cloud:
    #bus:
    #enabled: false
    config:
      server:
        native:
          search-locations: 'classpath:/config'

server:
  port: 8071
