spring:
  application:
    name: 'config'
  profiles:
    active: git

  cloud:
    bus:
      enabled: false
    config:
      server:
        git:
          uri: 'https://github.com/mikegrif/ms-configs.git'
          default-label: main
          timeout: 10
          clone-on-start: true
          force-pull: true
encrypt:
  key: 'just4MicroserviceSecret'

server:
  port: 8071
