services:
  accounts:
    image: 'mikegrif/accounts:latest'
    container_name: accounts-ms
    ports:
      - '8080:8080'
    deploy:
      resources:
        limits:
          memory: 1000m
    networks:
      - mikegrif_ntwk
  loans:
    image: 'mikegrif/loans:latest'
    container_name: loans-ms
    ports:
      - '8090:8090'
    deploy:
      resources:
        limits:
          memory: 1000m
    networks:
      - mikegrif_ntwk
  cards:
    image: 'mikegrif/cards:latest'
    container_name: cards-ms
    ports:
      - '9000:9000'
    deploy:
      resources:
        limits:
          memory: 1000m
    networks:
      - mikegrif_ntwk
networks:
  mikegrif_ntwk:
    driver: 'bridge'
